# -*- coding: utf-8 -*-
"""Day 4 assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oulDi3DUyT3B9tA6R3RX8njBTmiOWzv4
"""



# Convert Centigrade to Fahrenheit

import math
c = int(input("Centigrade:"))
f=int(c*9/5)+32
print('The temperature in Fahrenheit is ',f)

