# -*- coding: utf-8 -*-
"""Day 2 assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oulDi3DUyT3B9tA6R3RX8njBTmiOWzv4
"""

#to remove all the occurance of an element from a list
li = [1,2,3,4,4,5]
print(li)
list(filter(lambda a:a!=4, li))

#PROJECT : to generate a OTP

import random as r
import string
length = 6
otp = ''
characters = string.ascii_letters + string.digits
print(characters)

for i in range (length):
  otp = otp + r.choice(characters)
  print ('OTP :', otp)