# -*- coding: utf-8 -*-
"""Day 1 assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oulDi3DUyT3B9tA6R3RX8njBTmiOWzv4
"""

li=[int(i) for i in input ('enter the values:').split()]
li.sort()
print(li)

