# -*- coding: utf-8 -*-
"""Day 3 assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oulDi3DUyT3B9tA6R3RX8njBTmiOWzv4
"""

# Pangram check
import string
alphabet = set(string.ascii_lowercase)

def ispangram(string):
  return set(string.lower()) >= alphabet

  string = " The quick brown fox jumps over the lazy dog"
  if(ispangram(string)== True):
      print("Yes")
  else:
      print("No")

#lists of gifts given to respective person

person_list = {'1':2, '2':1, '3':4, '4':5, '5':3}
print(person_list.values())
person_list={1:2, 2:1, 3:4, 4:5 , 5:3, 3:2}
print(sorted(person_list))

